sudo: required

language: generic

services: 
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t henria18/multi-client ./client
  - docker build -t henria18/multi-nginx ./nginx
  - docker build -t henria18/multi-server ./server
  - docker build -t henria18/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to Docker Hub
  - docker push henria18/multi-client
  - docker push henria18/multi-nginx
  - docker push henria18/multi-server
  - docker push henria18/multi-worker